name: spooky
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pip
  - pip:
      - progressbar
      - torch
      - torchaudio
      - tqdm
      - einops
      - transformers
      - rotary_embedding_torch
      - librosa
      - inflect
      - unidecode
      - pymongo
      - python-dotenv
      - boto3
      - replicate
      - praw